### ISSUE TITLE
plugin paths in bower.json should start with src

### ISSUE THREAD

**Issue by babytei** [phuonghuynh/bubble-chart#2]
main": ["src/bubble-chart.js", "plugins/lines/lines.js", "plugins/central-click/central-click.js"],
should be 
main": ["src/bubble-chart.js", "src/plugins/lines/lines.js", "src/plugins/central-click/central-click.js"]

I have had issues using this with meteor-bower smart package as the paths do not exist

**Comment by phuonghuynh** [comment]
Done
