### ISSUE TITLE
Unable to run the example given

### ISSUE THREAD

**Issue by gc1e12** [phuonghuynh/bubble-chart#4]
I tried running the test/test-bubble0chart.html but it does not work. 
There seems to be a list of errors in the console.
![zz](https://cloud.githubusercontent.com/assets/5602657/6548810/34c7d426-c5fd-11e4-8101-8af5caee88ad.jpg)

**Comment by gc1e12** [comment]
Did I miss something?

**Comment by phuonghuynh** [comment]
Please prefer to http://gruntjs.com to build the project before run test
