### ISSUE TITLE
Does not work on some of the counts

### ISSUE THREAD

**Issue by specter8x** [phuonghuynh/bubble-chart#8]
I've changed some of the counts on the demo and it stops working. I used numbers like 6, 60, 74, etc.

**Comment by specter8x** [comment]
Further looking into the issue, it seems like it's in the randomCirclesPositions. It's going into infinite loop (intervalMax) for each value.

**Comment by phuonghuynh** [comment]
@specter8x you correct, bc it need to find somewhere in the big circle to stay, since it could not intersect on others, which is purpose of this design

We can have a minimum retry times for this

**Comment by specter8x** [comment]
How do you go around it? Reducing the intervalMax wouldn't work.

**Comment by phuonghuynh** [comment]
I think you should increase the `intersectDelta` which is used to calculate the intersection area
